[package]
name = "oh-bother"
version = "0.1.0"
authors = ["Matt Chun-Lum <mchunlum@gmail.com>"]

[[bin]]
bench = false
path = "src/main.rs"
name = "ob"

[profile.release]
lto = true

[dependencies]
clap = { version = "2.13.0", features = ["yaml"] }
hyper = "~0.9.10"
itertools = "0.5.2"
prettytable-rs = "^0.6"
rpassword = "0.3"
rustc-serialize = "*"
url = "*"
yaml-rust = "*"
