name: oh-bother
version: 1.0.0
about: Simple* JIRA interrupt management

settings:
  - SubcommandRequiredElseHelp
  - ColoredHelp

args:
  - debug:
      help: Enable debugging
      long: debug
      global: true
  - open:
      help: "Open in browser (enabled by default if set to true in config file)"
      short: o
      long: open
      global: true

# there is a special "config" arg that is added in the app
# itself since it requires a dynamic path value
subcommands:
  - setup:
      about: Create a config file
      settings:
        - ColoredHelp

  - list:
      about: Lists open interrupts
      settings:
        - ColoredHelp

  - current:
      about: Lists open interrupts assigned to you
      settings:
        - ColoredHelp

  - next:
      about: Lists available interrupts
      settings:
        - ColoredHelp

  - start:
      about: Start work on the specified interrupt
      settings:
        - ColoredHelp
      args:
        - issue:
            help: issue key
            index: 1
            required: true

  - stop:
      about: Stop work on the specified interrupt
      settings:
        - ColoredHelp
      args:
        - issue:
            help: issue key
            index: 1
            required: true

  - close:
      about: Close the specified interrupt
      settings:
        - ColoredHelp
      args:
        - issue:
            help: issue key
            index: 1
            required: true

  - new:
      about: Create a new interrupt
      settings:
        - ColoredHelp
      args:
        - summary:
            help: The summary for the new interrupt
            index: 1
            required: true
        - description:
            help: The description (conflicts with -D)
            short: d
            long: description
            takes_value: true
            conflicts_with: long_description
        - long_description:
            help: Write description in $EDITOR (conflicts with -d)
            short: D
            long: long-description
            conflicts_with: description
        - assignee:
            help: The assignee
            short: a
            long: assignee
            takes_value: true
        - label:
            help: Issue label (can be specified multiple times)
            short: l
            long: label
            multiple: true
            takes_value: true
        - project:
            help: The project key
            short: p
            long: project
            takes_value: true

  - issue:
      about: Look up an issue by it's key
      settings:
        - ColoredHelp
      args:
        - issue:
            help: issue key
            index: 1
            required: true

  - jql:
      about: Execute a raw jql query
      settings:
        - ColoredHelp
      args:
        - query:
            help: The JQL query
            index: 1
            required: true
